// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCen9ocj1K-UW5rieTCeMnIPv3CZMF4NiI',
    appId: '1:592640683409:web:a9d89c73c9a3ee4c2ebe30',
    messagingSenderId: '592640683409',
    projectId: 'flutter-worldtime',
    authDomain: 'flutter-worldtime.firebaseapp.com',
    storageBucket: 'flutter-worldtime.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAedJDZupAr_LRdA5EOYCGtTwcgVXv7A4U',
    appId: '1:592640683409:android:bc3367d92fb9f6af2ebe30',
    messagingSenderId: '592640683409',
    projectId: 'flutter-worldtime',
    storageBucket: 'flutter-worldtime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcF7slH5W1EpWYpM533FdJBXmT-F-aH00',
    appId: '1:592640683409:ios:137df58daf4aec792ebe30',
    messagingSenderId: '592640683409',
    projectId: 'flutter-worldtime',
    storageBucket: 'flutter-worldtime.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcF7slH5W1EpWYpM533FdJBXmT-F-aH00',
    appId: '1:592640683409:ios:4c6d8c7b0fdd7a1e2ebe30',
    messagingSenderId: '592640683409',
    projectId: 'flutter-worldtime',
    storageBucket: 'flutter-worldtime.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
